[package]
name = "lessbian_os"
version = "0.1.0"
authors = ["Chirag-droid <chirag.singla.pi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
