[toolchain]
# cargo `per-package-target` feature
channel = "nightly-2024-01-11"

# "bootloader" -> uefi format
# "kernel"     -> bare metal binary
targets = ["x86_64-unknown-uefi", "x86_64-unknown-none"]
